# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Codegen: UnsupportedModulePropertyParserError com @rnmapbox/maps é contornado pelo patch
# em patches/@rnmapbox+maps+10.2.10.patch (remove onLocationUpdate do Spec). Rode npm install antes de pod install.
# MapboxMaps 11.x exige iOS 14.0+; abaixo disso CocoaPods não resolve o pod.
platform :ios, '14.0'
plugin 'cocoapods-patch'

# Força MapboxMaps 10.x para compatibilidade entre @rnmapbox/maps e react-native-mapbox-navigation.
# react-native-mapbox-navigation usa MapboxNavigation 2.18.x que exige MapboxMaps ~> 10.17.0.
$RNMapboxMapsVersion = '~> 10.17.0'

pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MapboxNavigationExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :new_arch_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  target 'MapboxNavigationExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
     end
  end
end
